(() => {
 const $=id=>document.getElementById(id);
 const inputs=['client','brand','service','goal','situation'];
 const key='vision-guided-assistant-v1';let drafts={};
 const tools={presentation:['Abrir presentación','herramientas/presentacion.html'],pdf:['PDF de presentación ↓','herramientas/VISION-PRESENTACION-2026.pdf'],quote:['Abrir cotizador','herramientas/cotizador/index.html'],conditions:['Editar condiciones','herramientas/condiciones-servicio.html'],posts:['Ver publicaciones','#material-grafico'],brand:['Ver identidad','#identidad'],brochure:['Brochure y Canva','herramientas/brochure.html']};
 const routes={
 contact:{title:'Abre una conversación breve.',advice:'Presenta VISION y deja espacio para que la persona te cuente qué necesita.',steps:['Revisa qué vende el negocio y cómo se presenta.','Personaliza el saludo con el nombre o la marca.','Envía un solo mensaje y espera respuesta.'],tip:'No señales defectos de su cuenta ni prometas resultados que todavía no puedes sustentar.',message:c=>`${c.hello} Soy Miguel Ramos de VISION. Estamos a tu disposición si necesitas apoyo con redes sociales, diseño de marca o desarrollo web${c.brand?` para ${c.brand}`:''}. Gracias por tu tiempo.`,next:'interest',tools:['presentation']},
 interest:{title:'Entiende la necesidad antes de ofrecer.',advice:'Con tres datos puedes orientar mejor la conversación: objetivo, alcance y material disponible.',steps:['Pregunta qué quiere conseguir.','Confirma qué servicio y plataformas necesita.','Averigua si cuenta con fotos, videos e identidad visual.'],tip:'Para TikTok, define quién graba, cuántos videos necesita y cuántas revisiones se incluyen antes de dar un precio.',message:c=>`${c.hello} Gracias por tu interés en ${c.service}. Para orientarte mejor, cuéntame qué te gustaría conseguir, qué canales utilizas y si ya tienes fotos o videos disponibles. Con eso te puedo preparar una propuesta acorde a lo que necesitas.`,next:'present',tools:['presentation','brochure']},
 present:{title:'Conecta la presentación con su objetivo.',advice:'Envía el material con una frase que explique por qué le sirve a ese cliente.',steps:['Revisa que el servicio mencionado responda a su necesidad.','Adjunta el PDF de presentación.','Propón definir el alcance para preparar la cotización.'],tip:'Las cifras referenciales de la presentación son ejemplos de reporte. No las presentes como resultados garantizados ni casos reales.',message:c=>`${c.hello} Te comparto la presentación de VISION. Por lo que conversamos sobre ${c.goal}, podemos revisar una propuesta de ${c.service}${c.brand?` para ${c.brand}`:''}. ¿Te parece si definimos el alcance para cotizarlo?`,next:'quote',tools:['pdf','presentation']},
 quote:{title:'Prepara una propuesta concreta.',advice:'Usa la plantilla como punto de partida y revisa cada compromiso antes de enviarla.',steps:['Abre el cotizador y carga el servicio correspondiente.','Completa cliente, entregables, precio, moneda y vigencia.','Ajusta exclusiones, revisiones y condiciones. Revisa el PDF final.'],tip:'Comprueba que los horarios y condiciones de la cotización coincidan con el documento que enviarás. Las plantillas son editables y pueden tener alcances distintos.',message:c=>`${c.hello} Te envío la cotización de ${c.service}, pensada para ${c.goal}. Incluye el alcance, la inversión y las condiciones. Si necesitas ajustar algún entregable, lo revisamos antes de comenzar.`,next:'follow',tools:['quote','conditions']},
 follow:{title:'Retoma el tema sin presionar.',advice:'Un seguimiento breve debe facilitar que responda, no repetir toda la oferta.',steps:['Si acordaron una fecha, respétala.','Si no hay fecha, considera escribir tras 2 o 3 días hábiles.','Si sigue sin responder, deja un cierre amable y evita insistir repetidamente.'],tip:'No inventes urgencias, cupos limitados o descuentos para conseguir una respuesta.',message:c=>`${c.hello} Quería saber si te quedó alguna duda sobre ${c.service}. Si necesitas revisar el alcance o retomarlo más adelante, me comentas y lo coordinamos. 😊`,next:'close',tools:['quote','presentation']},
 price:{title:'Ajusta el alcance, no prometas más.',advice:'Primero identifica si la dificultad es el presupuesto o si no quedó claro qué incluye.',steps:['Pregunta qué presupuesto tenía previsto.','Explica qué entregables cubre la propuesta.','Si conviene, reduce entregables y prepara una nueva cotización.'],tip:'No apliques un descuento automático. Cualquier nuevo precio debe corresponder a un alcance que puedas cumplir.',message:c=>`${c.hello} Gracias por comentármelo. Podemos revisar el alcance de ${c.service} y priorizar lo más importante para ${c.goal}. ¿Qué presupuesto tenías previsto? Así veo qué alternativa puedo ofrecerte.`,next:'quote',tools:['quote']},
 close:{title:'Deja el inicio bien definido.',advice:'Antes de comenzar, el cliente debe conocer y aceptar lo que incluye el servicio y su forma de pago.',steps:['Revisa los datos y el alcance aprobados.','Personaliza y envía las condiciones del servicio.','Confirma la aceptación, el pago acordado y la fecha de inicio.'],tip:'Enviar las condiciones no equivale a recibir conformidad. Conserva la respuesta del cliente junto a la propuesta.',message:c=>`${c.hello} ¡Gracias por confiar en VISION! Te comparto las condiciones para comenzar con ${c.service}. Revísalas y confirma tu conformidad. Luego coordinamos el pago y la fecha de inicio.`,next:'start',tools:['conditions','quote']},
 start:{title:'Reúne el material para empezar.',advice:'Organiza la información antes de producir para evitar retrasos y correcciones innecesarias.',steps:['Pide logo, fotos, videos e información actualizada del negocio.','Define el objetivo, el calendario y la persona que aprobará.','Coordina los permisos de acceso que realmente necesitas.'],tip:'Usa permisos de administración cuando la plataforma lo permita. No guardes contraseñas en las notas del centro.',message:c=>`${c.hello} Para comenzar con ${c.service}${c.brand?` para ${c.brand}`:''}, envíame el logo, fotos o videos disponibles, servicios y promociones vigentes. También coordinemos quién revisará el contenido y la fecha de inicio.`,next:'content',tools:['conditions','posts','brand']},
 content:{title:'Publica algo que ayude a decidir.',advice:'Elige una pregunta frecuente del cliente y respóndela con un ejemplo concreto.',steps:['Escoge una sola pregunta real sobre el servicio.','Usa una plantilla de VISION y coloca un titular corto.','Revisa la legibilidad y cierra con una invitación a consultar.'],tip:'Alterna contenido útil, trabajos reales y servicios. Las composiciones de ejemplo del centro deben adaptarse antes de publicarlas como portafolio.',message:c=>`¿Qué necesitas para empezar con ${c.service}?\n\nPrimero definimos tu objetivo, revisamos el material disponible y acordamos el alcance del trabajo. Así tendrás claro qué incluye tu propuesta desde el inicio.\n\nEscríbenos y cuéntanos qué quieres mejorar.`,next:'contact',tools:['posts','brand']}
 };
 function context(){return{hello:$('guide-client').value.trim()?`Hola, ${$('guide-client').value.trim()} 👋`:'Hola 👋',brand:$('guide-brand').value.trim(),service:$('guide-service').value.toLowerCase(),goal:$('guide-goal').value.trim()||'mejorar la presencia digital de tu negocio'};}
 function draftKey(){return JSON.stringify(inputs.map(k=>$('guide-'+k).value));}
 function persist(){try{localStorage.setItem(key,JSON.stringify({values:Object.fromEntries(inputs.map(k=>[k,$('guide-'+k).value])),drafts}));}catch(_){$('guide-status').textContent='El navegador no permite guardar. Puedes descargar tu nota.';}}
 try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved&&saved.values){inputs.forEach(k=>{if(typeof saved.values[k]==='string')$('guide-'+k).value=saved.values[k];});if(!routes[$('guide-situation').value])$('guide-situation').value='contact';if(!$('guide-service').value)$('guide-service').selectedIndex=0;drafts=saved.drafts&&typeof saved.drafts==='object'?saved.drafts:{};}}catch(_){}
 function render(){const route=routes[$('guide-situation').value]||routes.contact;const c=context();$('guide-title').textContent=route.title;$('guide-advice').textContent=route.advice;$('guide-tip').textContent=route.tip;$('guide-steps').replaceChildren();route.steps.forEach(text=>{const li=document.createElement('li');li.textContent=text;$('guide-steps').append(li);});$('guide-message').value=drafts[draftKey()]??route.message(c);$('guide-tools').replaceChildren();route.tools.forEach(k=>{const [text,href]=tools[k];const a=document.createElement('a');a.textContent=text;a.href=href;if(!href.startsWith('#')){a.target='_blank';a.rel='noopener';}if(k==='pdf')a.download='VISION-PRESENTACION-2026.pdf';$('guide-tools').append(a);});$('guide-next').textContent='Siguiente: '+$('guide-situation').querySelector(`[value="${route.next}"]`).textContent;$('guide-status').textContent='Recomendación preparada según la situación elegida.';persist();}
 inputs.forEach(k=>$('guide-'+k).addEventListener('change',render));
 $('guide-form').addEventListener('submit',e=>{e.preventDefault();render();$('guide-answer').scrollIntoView({behavior:'smooth',block:'start'});});
 $('guide-message').addEventListener('input',()=>{drafts[draftKey()]=$('guide-message').value;persist();});
 $('guide-next').onclick=()=>{const route=routes[$('guide-situation').value];$('guide-situation').value=route.next;render();};
 $('guide-copy').onclick=async()=>{const text=$('guide-message').value;try{await navigator.clipboard.writeText(text);$('guide-status').textContent='Texto copiado. Revísalo antes de enviarlo.';}catch(_){$('guide-message').focus();$('guide-message').select();const ok=document.execCommand('copy');$('guide-status').textContent=ok?'Texto copiado.':'Texto seleccionado: usa Ctrl+C o ⌘C para copiar.';}};
 $('guide-download').onclick=()=>{const route=routes[$('guide-situation').value];const text=`VISION · Nota de trabajo\nCliente: ${$('guide-client').value||'Sin indicar'}\nMarca: ${$('guide-brand').value||'Sin indicar'}\nServicio: ${$('guide-service').value}\n\n${route.title}\n${route.advice}\n\n${route.steps.map((t,i)=>`${i+1}. ${t}`).join('\n')}\n\nTen en cuenta: ${route.tip}\n\nTexto para el cliente:\n${$('guide-message').value}\n`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='VISION-nota-cliente.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('guide-status').textContent='Nota descargada.';};
 $('guide-new').onclick=()=>{if(!confirm('¿Limpiar los datos y textos guardados de este asistente? Descarga tu nota si quieres conservarlos.'))return;drafts={};['client','brand','goal'].forEach(k=>$('guide-'+k).value='');$('guide-situation').value='contact';$('guide-service').selectedIndex=0;render();};
 // Preserve the existing process checklists on the same browser.
 document.querySelectorAll('.panel input[type=checkbox]').forEach((el,i)=>{const k='vision-process-check-'+i;try{el.checked=localStorage.getItem(k)==='true';}catch(_){}el.addEventListener('change',()=>{try{localStorage.setItem(k,String(el.checked));}catch(_){}});});
 render();
})();
